databases:
  - name: timer-db
    databaseName: yoga_timer_api_production
    user: yoga_timer_user

services:
  - type: web
    name: timer-api
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: timer-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: WEB_CONCURRENCY
        value: 2
